name: Build Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Windows Binary
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src
        spec: app.spec

    - name: Generate Linux Binary
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: src
        spec: app.spec

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src/dist/windows/*
          src/dist/linux/*
        tag_name: ${{ github.sha }}
        body: |
          Release ${{ github.sha }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        