name: Build Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Windows Binary
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .
        spec: app.spec

    - uses: actions/upload-artifact@v2
      with:
        name: Windows Binary
        path: dist/

    - name: Generate Linux Binary
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: .
        spec: app.spec

    - uses: actions/upload-artifact@v2
      with:
        name: Linux Binary
        path: dist/
      