name: Build and release

on:
  push:
    branches:
      - main  # Change this to your main branch name

permissions:
  contents: write
  
jobs:
  build-windows-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Windows Binary
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src
        spec: app.spec

    - name: List the dist folder
      working-directory: src
      run: |
        ls dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-dist
        path: |
          src/dist/windows/*

  build-linux-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Linux Binary
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: src
        spec: app.spec

    - name: List the dist folder
      working-directory: src
      run: |
        ls dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-dist
        path: |
          src/dist/linux/*
  
  build-macos-release:
    runs-on: macos-13
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install requirements
      working-directory: src
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate MacOS Binary
      working-directory: src
      run: |
        pyinstaller app.spec

    - name: List the dist folder
      working-directory: src
      run: |
        ls dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-dist
        path: src/dist/*

  create-release:
    needs: [build-linux-release, build-macos-release, build-windows-release]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: src/tmp

    - name: Move artifacts
      run: |
        mkdir src/dist
        mv src/tmp/macos-dist/iCloud.Keychain.to.BitWarden src/dist/iCloud.Keychain.to.BitWarden-macOS
        mv src/tmp/windows-dist/iCloud.Keychain.to.Bitwarden.exe src/dist/iCloud.Keychain.to.Bitwarden-Windows.exe
        mv src/tmp/linux-dist/* src/dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src/dist/*
        tag_name: ${{ github.run_number }}.${{ github.run_attempt }}
        body: |
          Release ${{ github.run_number }}.${{ github.run_attempt }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}