name: Build Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Change this to your Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
    - name: Build the application
      run: |
        pyinstaller app.spec
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*